### ISSUE TITLE
USER STORY: Admin poll management

### ISSUE THREAD

**Issue by rimanfarhood** [rimanfarhood/Agile#6]
In order to automatically mange the poll state as an administrator, I can pick the expiry date while publishing the poll

## Acceptance Criteria:

- Acceptance Criteria 1: The poll should disappear att 00:00 AM on the selected date
- Acceptance Criteria 2: The poll should appear on the home page
- Acceptance Criteria 3: A message displayed informing the user about the current poll state

## Tasks

- [ ] Update the admin view: The poll design HTML & CSS to  incl.  date picker
- [ ] Create a job to check expired Polls everyday at 00:00 AM
- [ ] Create a JS function to validate the expiry date is the selected date
